"""
Executors for running plans generated by planners.

An Executor is responsible for executing a structured Plan by running each step
and handling dependencies, errors, and status tracking.
"""

import asyncio
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Union

from hotlm_agents.planning.plan import Plan, PlanResult, PlanStep, StepStatus
from hotlm_agents.tooling.registry import ToolRegistry
from hotlm_core.errors import HotLMToolError


class BaseExecutor(ABC):
    """
    Base class for plan executors.
    
    An Executor takes a Plan and executes its steps, respecting dependencies
    and handling errors.
    """
    
    @abstractmethod
    async def execute_plan(self, plan: Plan, tools: ToolRegistry) -> PlanResult:
        """
        Execute a plan using the available tools.
        
        Args:
            plan: The plan to execute
            tools: Registry of available tools
            
        Returns:
            The result of executing the plan
        """
        pass

class SimpleExecutor(BaseExecutor):
    """
    A simple sequential executor for plans.
    
    This executor runs plan steps in sequence, respecting dependencies.
    """
    
    def __init__(self, max_retries: int = 0):
        """
        Initialize the simple executor.
        
        Args:
            max_retries: Maximum number of retries for failed steps (0 = no retries)
        """
        self.max_retries = max_retries
    
    async def execute_plan(self, plan: Plan, tools: ToolRegistry) -> PlanResult:
        """
        Execute a plan sequentially, respecting dependencies.
        
        Args:
            plan: The plan to execute
            tools: Registry of available tools
            
        Returns:
            The result of executing the plan
        """
        while not plan.is_complete():
            # Get steps that are ready to run
            runnable_steps = plan.get_runnable_steps()
            
            if not runnable_steps:
                # If no steps are runnable but the plan isn't complete,
                # there's a circular dependency or all remaining steps have failed dependencies
                return PlanResult(
                    plan=plan,
                    success=False,
                    error="Execution blocked: circular dependency or failed dependencies"
                )
            
            # Execute each runnable step
            for step in runnable_steps:
                await self._execute_step(step, tools, plan)
        
        # Check if the plan succeeded (no failed steps)
        success = not plan.has_failed_steps()
        error = "One or more steps failed" if not success else None
        
        # Create a summary of the execution
        summary = self._create_execution_summary(plan)
        
        return PlanResult(
            plan=plan,
            success=success,
            error=error,
            summary=summary
        )
    
    async def _execute_step(
        self, 
        step: PlanStep, 
        tools: ToolRegistry, 
        plan: Plan,
        retry_count: int = 0
    ) -> None:
        """Execute a single step of the plan."""
        # Mark the step as in progress
        step.status = StepStatus.IN_PROGRESS
        
        try:
            # Check if the tool exists
            if step.tool_name not in tools:
                raise HotLMToolError(f"Tool '{step.tool_name}' not found in registry")
            
            # Execute the tool
            tool = tools.get_tool(step.tool_name)
            result = await tool.ainvoke(step.tool_args)
            
            # Update the step with the result
            step.result = result
            step.status = StepStatus.SUCCEEDED
            
        except Exception as e:
            # Handle step failure
            step.error = str(e)
            
            # Retry logic
            if retry_count < self.max_retries:
                # Reset the step status and retry
                step.status = StepStatus.PENDING
                await self._execute_step(step, tools, plan, retry_count + 1)
            else:
                # Mark as failed if we've exhausted retries
                step.status = StepStatus.FAILED
    
    def _create_execution_summary(self, plan: Plan) -> str:
        """Create a human-readable summary of the plan execution."""
        success_count = sum(1 for step in plan.steps if step.status == StepStatus.SUCCEEDED)
        fail_count = sum(1 for step in plan.steps if step.status == StepStatus.FAILED)
        
        summary = [
            f"Plan execution completed with {success_count} successful steps and {fail_count} failed steps.",
            f"Plan description: {plan.description}",
            "\nStep results:"
        ]
        
        for step in plan.steps:
            status = step.status.value.upper()
            summary.append(f"- {step.id}: {status} - {step.description}")
            
            if step.result:
                # Truncate long results
                result = step.result
                if len(result) > 100:
                    result = result[:97] + "..."
                summary.append(f"  Result: {result}")
                
            if step.error:
                summary.append(f"  Error: {step.error}")
        
        return "\n".join(summary)

class ParallelExecutor(BaseExecutor):
    """
    A parallel executor for plans.
    
    This executor runs independent steps in parallel, maximizing throughput
    while respecting dependencies.
    """
    
    def __init__(self, max_concurrency: int = 5, max_retries: int = 0):
        """
        Initialize the parallel executor.
        
        Args:
            max_concurrency: Maximum number of steps to execute concurrently
            max_retries: Maximum number of retries for failed steps (0 = no retries)
        """
        self.max_concurrency = max_concurrency
        self.max_retries = max_retries
    
    async def execute_plan(self, plan: Plan, tools: ToolRegistry) -> PlanResult:
        """
        Execute a plan with parallel execution where possible.
        
        Args:
            plan: The plan to execute
            tools: Registry of available tools
            
        Returns:
            The result of executing the plan
        """
        while not plan.is_complete():
            # Get steps that are ready to run
            runnable_steps = plan.get_runnable_steps()
            
            if not runnable_steps:
                # If no steps are runnable but the plan isn't complete,
                # there's a circular dependency or all remaining steps have failed dependencies
                return PlanResult(
                    plan=plan,
                    success=False,
                    error="Execution blocked: circular dependency or failed dependencies"
                )
            
            # Limit the number of concurrent executions
            batch = runnable_steps[:self.max_concurrency]
            
            # Execute the batch in parallel
            tasks = [self._execute_step(step, tools, plan) for step in batch]
            await asyncio.gather(*tasks)
        
        # Check if the plan succeeded (no failed steps)
        success = not plan.has_failed_steps()
        error = "One or more steps failed" if not success else None
        
        # Create a summary of the execution
        summary = self._create_execution_summary(plan)
        
        return PlanResult(
            plan=plan,
            success=success,
            error=error,
            summary=summary
        )
    
    async def _execute_step(
        self, 
        step: PlanStep, 
        tools: ToolRegistry, 
        plan: Plan,
        retry_count: int = 0
    ) -> None:
        """Execute a single step of the plan."""
        # Mark the step as in progress
        step.status = StepStatus.IN_PROGRESS
        
        try:
            # Check if the tool exists
            if step.tool_name not in tools:
                raise HotLMToolError(f"Tool '{step.tool_name}' not found in registry")
            
            # Execute the tool
            tool = tools.get_tool(step.tool_name)
            result = await tool.ainvoke(step.tool_args)
            
            # Update the step with the result
            step.result = result
            step.status = StepStatus.SUCCEEDED
            
        except Exception as e:
            # Handle step failure
            step.error = str(e)
            
            # Retry logic
            if retry_count < self.max_retries:
                # Reset the step status and retry
                step.status = StepStatus.PENDING
                await self._execute_step(step, tools, plan, retry_count + 1)
            else:
                # Mark as failed if we've exhausted retries
                step.status = StepStatus.FAILED
    
    def _create_execution_summary(self, plan: Plan) -> str:
        """Create a human-readable summary of the plan execution."""
        success_count = sum(1 for step in plan.steps if step.status == StepStatus.SUCCEEDED)
        fail_count = sum(1 for step in plan.steps if step.status == StepStatus.FAILED)
        
        summary = [
            f"Plan execution completed with {success_count} successful steps and {fail_count} failed steps.",
            f"Plan description: {plan.description}",
            "\nStep results:"
        ]
        
        for step in plan.steps:
            status = step.status.value.upper()
            summary.append(f"- {step.id}: {status} - {step.description}")
            
            if step.result:
                # Truncate long results
                result = step.result
                if len(result) > 100:
                    result = result[:97] + "..."
                summary.append(f"  Result: {result}")
                
            if step.error:
                summary.append(f"  Error: {step.error}")
        
        return "\n".join(summary)